### ISSUE TITLE
PSAR vs TV PSAR

### ISSUE THREAD

**Issue by anwebdevelopers** [ixjb94/indicators#12]
Hello! Can you help me with the PSAR indicator? I can't get the same result as TradingView. I can't figure out what length the high and low input data should be?

**Comment by ixjb94** [comment]
Hi @anwebdevelopers 😊

I've double checked the indicator and TradingView the results indeed are different but the calculations are correct.    
They are different because tradingview is implementing it differently.

here are the results:
```js
{
  '0': 39789.3478992606,
  '1': 39779.286554734004,
  '2': 39768.10728303778,
  '3': 39755.685870041976,
  '4': 39741.88430004664,
  'name': 'technicalindicators'
}

{
  '0': 39789.3478992606,
  '1': 39779.286554734004,
  '2': 39768.10728303778,
  '3': 39755.685870041976,
  '4': 39741.88430004664,
  'name': '@ixjb94/indicators'
}
```
TradingView:
![image](https://github.com/ixjb94/indicators/assets/121232430/d653c124-ff1e-4585-b3c0-86cc6111846d)

The difference ("error"?) between us and tradingview (which is negligible) :
0: 0.04%
1: 0.04%
2: 0.04%
3: 0.04%
4: 0.04%

But If you really want to achieve that number (or being really close to that number), you can use these parameters:
```js
await ta.psar(highs, lows, 0.025, 0.2)
```

Results:
```js
{
  '0': 39806.288131458794,
  '1': 39795.77215023862,
  '2': 39783.753885987,
  '3': 39770.01872684228,
  '4': 39754.32140210547,
  name: '@ixjb94/indicators'
}
```

![image](https://github.com/ixjb94/indicators/assets/121232430/0e0734b7-b6d0-4d42-8cc5-faabdb634eb6)

**Comment by anwebdevelopers** [comment]
Thank you for trying to figure it out) How does tradingview make calculations...
