### ISSUE TITLE
Async Functions

### ISSUE THREAD

**Issue by TimUnderhay** [ixjb94/indicators#16]
Thank you for this library!  I hope it won't be too cheeky to offer a wee bit of feedback -- marking the functions as async offers no advantage as all the code I can see is all synchronous.  Users will end up awaiting the results for no discernible benefit.  Not a big deal, but it can complicate things if running inside complex loops, causing the caller to have to await every layer up the call stack up to that point.

**Comment by ixjb94** [comment]
@TimUnderhay Hi 😊,
You are absolutely right about the calculations that are synchronous however I did that because I was doing some heavy calculations and I needed to take advantage of `Promise.all` that's why I marked them as `async`.    
But if you need them to be `sync` and **NOT**  `async` I can make another version of it for you 🤗

**Comment by ixjb94** [comment]
Added `Sync` https://github.com/ixjb94/indicators/commit/1b86f10bb37e8203e9cc138119c4e136a0c2f76c version.    
Now there are two versions of each `indicators` and `indicatorsNormalized`:    
```js
1- Indicators: new Indicators()
2- IndicatorsNormalized: new IndicatorsNormalized()
3- IndicatorsSync: new IndicatorsSync()
4- IndicatorsNormalizedSync: new IndicatorsNormalizedSync()
```

**Comment by TimUnderhay** [comment]
@ixjb94 I probably wouldn't have taken you up on the offer as it wasn't really an issue for me, but I offer my thanks all the same.
