### ISSUE TITLE
Does it handle decimals?

### ISSUE THREAD

**Issue by Vasile-Peste** [ixjb94/indicators#2]
Hello, I'm wondering if floating point error/decimal calculations are handled under the hood?

**Comment by ixjb94** [comment]
Hi @Vasile-Peste 😊, 
As you can see in this image, the floating precision is not handled by the library (because of performance)
![image](https://github.com/ixjb94/indicators/assets/121232430/e1397124-c93c-48bb-8e01-397628591106)

But i never had any trouble with it because it's negligible.
I think it's better to handle it at the latest layer if you want to use it for trading bots.

Here is a sample data you can play with (rename it to .js):
[dataParsed.txt](https://github.com/ixjb94/indicators/files/11478058/dataParsed.txt)

And here is how to test the library: 
```js
import { open, high, low, close, volume } from "./dataParsed.js"
import { IndicatorsNormalized } from "@ixjb94/indicators"

const ta = new IndicatorsNormalized()

Run()
async function Run() {
    const result = await ta.sma(close, 50)
    console.log(result)
}
```

**Comment by Vasile-Peste** [comment]
I see, it's clear!

Thank you
